name: "Docker Build and Deploy"
on:
  release:
    types: [published]
  push:
    branches:
      - master
      - develop
      - implement-cd
    tags:
      - v*
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build & Publish (master branch)
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          tags: hacksocnotts/discord-membership-bot/bot:latest,hacksocnotts/discord-membership-bot/bot:${{ steps.server-version.outputs.current-version}}
        if: ${{ github.ref == 'master' }}

      - name: Build & Publish (other refs)
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          tags: hacksocnotts/discord-membership-bot/bot:${{ steps.server-version.outputs.current-version}}
        if: ${{ github.ref != 'master' }}
