name: Build, Lint, and Test

on: [push]

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install Dependencies
        uses: bahmutov/npm-install@v1

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('yarn.lock') }}
          # loading an older version is fine here, since it will get an npm install
          restore-keys: |
            node_modules-

  build:
    needs: install
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Load node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('yarn.lock') }}
          # no restore-keys here, so we only accept this exact version

      - name: Compile Production Build
        run: yarn build

  lint:
    needs: install
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Load node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('yarn.lock') }}
          # no restore-keys here, so we only accept this exact version

      - name: Run eslint
        run: yarn lint

  test:
    needs: install
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Load node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('yarn.lock') }}
          # no restore-keys here, so we only accept this exact version

      - name: Run Jest
        run: yarn test
